import Foundation

/// Original, concise guides informed by reward-based RSPCA, Dogs Trust and Blue Cross guidance.
/// No guide predicts outcomes or replaces individual professional advice.
enum BuiltInTrickLibrary {
    static let tricks: [TrickDefinition] = [
        make("sentado", String(localized: "Sentado"), "figure.seated.side", .easy, .basic,
             objective: String(localized: "Sentarse voluntariamente al oír una señal."),
             steps: [String(localized: "Acerca un premio a la nariz y muévelo despacio hacia arriba y ligeramente atrás."), String(localized: "En cuanto apoye el trasero, di «bien» y entrega el premio. No empujes la cadera."), String(localized: "Cuando anticipe el gesto, di «sentado» antes de hacerlo. Reduce la ayuda de la mano.")],
             mistakes: [String(localized: "Elevar tanto el premio que tenga que saltar."), String(localized: "Pedir la postura muchas veces seguidas sin pausa.")],
             progression: String(localized: "Se sienta con un gesto pequeño; después prueba la señal en otra habitación."),
             precautions: String(localized: "Usa suelo antideslizante. Si sentarse parece incómodo, detén el ejercicio.")),
        make("quieto", String(localized: "Quieto"), "hand.raised", .medium, .safety, prerequisites: [String(localized: "Sentado o Tumba")],
             objective: String(localized: "Mantener una postura cómoda hasta la señal de terminar."),
             steps: [String(localized: "Pide una postura conocida, espera un instante y recompensa sin alejarte."), String(localized: "Añade «quieto» y una señal de terminar, como «ya». Libera antes de que se levante."), String(localized: "Amplía primero el tiempo, luego la distancia y por último las distracciones, de una en una.")],
             mistakes: [String(localized: "Aumentar tiempo y distancia a la vez."), String(localized: "Regañar si se mueve; vuelve a una versión más fácil.")],
             progression: String(localized: "Permanece relajado unos segundos mientras das un paso y regresas."),
             precautions: String(localized: "Practica en un recinto seguro; esta señal nunca sustituye la correa cerca del tráfico.")),
        make("ven-aqui", String(localized: "Ven aquí"), "arrow.down.to.line", .medium, .safety,
             objective: String(localized: "Acercarse con confianza cuando lo llamas."),
             materials: String(localized: "Premios valiosos; fuera de casa, arnés y correa larga en una zona segura."),
             steps: [String(localized: "A poca distancia y sin distracciones, di su nombre y «ven aquí» una sola vez."), String(localized: "Retrocede un par de pasos para invitarlo a acercarse. Recompensa cuando llegue."), String(localized: "Permite que vuelva a explorar. Aumenta la distancia poco a poco manteniendo la seguridad.")],
             mistakes: [String(localized: "Llamar para regañar o terminar siempre la diversión."), String(localized: "Repetir la señal si la distracción es demasiado difícil.")],
             progression: String(localized: "Acude desde una distancia corta en varios entornos tranquilos."),
             precautions: String(localized: "No sueltes la correa para comprobar si funciona. Evita tirones y no lo persigas.")),
        make("tumba", String(localized: "Tumba"), "arrow.down", .easy, .basic, prerequisites: [String(localized: "Sentado, si resulta cómodo")],
             objective: String(localized: "Tumbarse de forma relajada al recibir una señal."),
             steps: [String(localized: "Desde una postura cómoda, baja un premio desde la nariz hacia el suelo."), String(localized: "Deslízalo ligeramente hacia delante. Premia cualquier avance y, después, los codos apoyados."), String(localized: "Añade «tumba» antes del gesto cuando lo comprenda y retira gradualmente el señuelo.")],
             mistakes: [String(localized: "Tirar de las patas o presionar el cuerpo."), String(localized: "Mover el premio demasiado deprisa.")],
             progression: String(localized: "Se tumba siguiendo un gesto breve sin necesidad de comida visible."),
             precautions: String(localized: "Ofrece una superficie blanda y firme. No insistas si evita apoyar el cuerpo.")),
        make("dejalo", String(localized: "Déjalo"), "hand.raised.slash", .medium, .safety,
             objective: String(localized: "Apartarse voluntariamente de un objeto antes de cogerlo."),
             steps: [String(localized: "Presenta un premio dentro de una mano cerrada, sin acercarla a su cara."), String(localized: "En cuanto aparte la nariz, marca y premia desde la otra mano. Si se frustra, aumenta la distancia."), String(localized: "Añade «déjalo» antes de presentar la mano. Practica después con un objeto seguro a distancia.")],
             mistakes: [String(localized: "Usar algo peligroso para practicar."), String(localized: "Dejar el objeto demasiado cerca o inaccesible durante demasiado tiempo.")],
             progression: String(localized: "Aparta su atención de un objeto sencillo y te mira esperando su premio."),
             precautions: String(localized: "Gestiona el entorno para evitar ingestiones. Si protege objetos, pide ayuda profesional sin confrontarlo.")),
        make("suelta", String(localized: "Suelta"), "arrow.up.forward.square", .medium, .safety,
             objective: String(localized: "Soltar un juguete a cambio de algo que valore."),
             materials: String(localized: "Juguete seguro y un premio o segundo juguete de valor similar o mayor."),
             steps: [String(localized: "Mientras tiene un juguete sencillo, presenta un intercambio atractivo a su lado."), String(localized: "Cuando abra la boca, di «bien», entrega el premio y recoge el juguete con calma."), String(localized: "Devuelve el juguete cuando sea seguro. Añade «suelta» justo antes de ofrecer el intercambio.")],
             mistakes: [String(localized: "Perseguirlo o tirar del objeto para quitárselo."), String(localized: "Quitar siempre el juguete al terminar.")],
             progression: String(localized: "Suelta un juguete conocido con la señal y recibe después su recompensa."),
             precautions: String(localized: "No metas la mano en su boca. Si se queda rígido o protege el objeto, detente y consulta.")),
        make("junto", String(localized: "Junto"), "figure.walk", .advanced, .coexistence,
             objective: String(localized: "Caminar unos pasos a tu lado con la correa floja."),
             materials: String(localized: "Arnés cómodo, correa sin tensión y premios pequeños."),
             steps: [String(localized: "En un lugar tranquilo, premia cuando esté junto a tu pierna por propia iniciativa."), String(localized: "Da un paso y recompensa cerca de tu lado si te acompaña con la correa floja."), String(localized: "Añade «junto» y encadena pocos pasos. Alterna con ratos de olfateo libre y seguro.")],
             mistakes: [String(localized: "Exigir atención constante durante todo el paseo."), String(localized: "Corregir con tirones al cambiar de dirección.")],
             progression: String(localized: "Camina varios pasos relajado junto a ti con pocas distracciones."),
             precautions: String(localized: "La comodidad y el olfateo forman parte del paseo. Aumenta la distancia de lo que lo altere.")),
        make("a-tu-sitio", String(localized: "A tu sitio"), "house", .medium, .coexistence,
             objective: String(localized: "Acudir a una manta o cama y sentirse cómodo allí."),
             materials: String(localized: "Manta o cama estable en una zona tranquila y premios."),
             steps: [String(localized: "Coloca la manta y recompensa que se acerque o la pise voluntariamente."), String(localized: "Entrega los premios sobre ella; después premia que permanezca o se tumbe."), String(localized: "Di «a tu sitio» antes de que vaya. Añade una señal para salir y aumenta el tiempo con calma.")],
             mistakes: [String(localized: "Usar la cama como castigo."), String(localized: "Esperar mucha duración cuando aún está aprendiendo.")],
             progression: String(localized: "Busca la manta con una señal y permanece relajado unos instantes."),
             precautions: String(localized: "Debe poder alejarse. No encierres ni fuerces la permanencia.")),
        make("pata", String(localized: "Pata"), "pawprint", .easy, .fun, prerequisites: [String(localized: "Sentado cómodo")],
             objective: String(localized: "Apoyar brevemente una pata en tu mano por iniciativa propia."),
             steps: [String(localized: "Presenta una mano cerrada con un premio a baja altura y espera un movimiento de pata."), String(localized: "Marca cualquier pequeño levantamiento y premia; después, el contacto suave con tu mano."), String(localized: "Ofrece la mano vacía y premia con la otra. Añade «pata» antes del gesto.")],
             mistakes: [String(localized: "Agarrar o mantener levantada la pata."), String(localized: "Insistir si solo olfatea o pierde interés.")],
             progression: String(localized: "Toca suavemente la mano abierta después de una señal."),
             precautions: String(localized: "Mantén la mano baja y suelta enseguida. Detente si pierde equilibrio o muestra incomodidad.")),
        make("toca", String(localized: "Toca"), "hand.point.up.left", .easy, .basic,
             objective: String(localized: "Tocar tu mano suavemente con la nariz."),
             steps: [String(localized: "Ofrece la palma abierta a pocos centímetros, a un lado de su nariz."), String(localized: "Cuando se acerque y la toque, marca y recompensa desde la otra mano."), String(localized: "Retira y vuelve a presentar la mano. Añade «toca» y cambia ligeramente su posición.")],
             mistakes: [String(localized: "Empujar la mano contra el hocico."), String(localized: "Pedir que siga la mano demasiado lejos al principio.")],
             progression: String(localized: "Busca la palma vacía con la nariz desde pequeñas distancias."),
             precautions: String(localized: "Deja espacio para retirarse y evita acercarte de frente si le incomoda.")),
        make("gira", String(localized: "Gira"), "arrow.clockwise", .medium, .fun,
             objective: String(localized: "Dar un giro amplio y suave siguiendo una señal."),
             steps: [String(localized: "Con las cuatro patas en el suelo, guía la nariz con un premio en un arco amplio."), String(localized: "Premia primero un cuarto de giro y después una vuelta cómoda completa."), String(localized: "Añade «gira» y reduce el gesto. Haz pocas repeticiones y una pausa.")],
             mistakes: [String(localized: "Trazar círculos pequeños o mover el premio con rapidez."), String(localized: "Encadenar giros repetidos.")],
             progression: String(localized: "Completa una vuelta lenta con un gesto pequeño sin perder equilibrio."),
             precautions: String(localized: "Evita suelos resbaladizos. Omite este truco si hay dolor, rigidez o problemas de movilidad.")),
        make("espera", String(localized: "Espera"), "pause", .medium, .safety,
             objective: String(localized: "Hacer una pausa breve antes de avanzar con permiso."),
             steps: [String(localized: "Ante una puerta interior cerrada, recompensa un instante de calma."), String(localized: "Di «espera» y mueve el pomo ligeramente; premia si permanece. Reduce el movimiento si avanza."), String(localized: "Abre un poco y usa «ya» para avanzar juntos. Amplía la apertura progresivamente.")],
             mistakes: [String(localized: "Usar una puerta a la calle como primera práctica."), String(localized: "Cerrar la puerta sobre el perro para impedirle pasar.")],
             progression: String(localized: "Hace una pausa breve con una puerta interior abierta hasta que lo invitas a pasar."),
             precautions: String(localized: "Mantén barreras físicas o correa en salidas al exterior. No confíes solo en una señal.")),
        make("mirame", String(localized: "Mírame"), "eye", .easy, .basic,
             objective: String(localized: "Orientar brevemente la atención hacia ti de manera voluntaria."),
             steps: [String(localized: "En un entorno tranquilo, espera a que te mire y marca ese instante."), String(localized: "Entrega un premio y deja que vuelva a mirar alrededor."), String(localized: "Añade «mírame» cuando puedas anticipar la mirada. Pide solo un momento al principio.")],
             mistakes: [String(localized: "Mantener una mirada fija o invadir su espacio."), String(localized: "Pedir atención cuando la distracción lo supera.")],
             progression: String(localized: "Te mira un instante al oír la señal con distracciones leves y a distancia."),
             precautions: String(localized: "No exijas contacto visual prolongado. Acepta una orientación cómoda de la cabeza.")),
        make("busca", String(localized: "Busca"), "magnifyingglass", .easy, .fun,
             objective: String(localized: "Buscar pequeños premios con el olfato en una zona segura."),
             materials: String(localized: "Premios apropiados y una superficie limpia sin objetos que pueda ingerir."),
             steps: [String(localized: "Deja un premio a la vista en el suelo y di «busca» mientras señalas la zona."), String(localized: "Permite que lo encuentre sin dirigir cada movimiento."), String(localized: "Coloca después dos o tres premios fáciles de localizar y oculta alguno solo parcialmente.")],
             mistakes: [String(localized: "Esconder los premios en lugares demasiado difíciles."), String(localized: "Ayudar constantemente o apresurar la búsqueda.")],
             progression: String(localized: "Explora con calma y encuentra premios parcialmente ocultos cerca."),
             precautions: String(localized: "Supervisa la búsqueda, evita tóxicos y adapta los premios a su alimentación.")),
        make("trae", String(localized: "Trae"), "arrow.uturn.backward", .advanced, .fun, prerequisites: [String(localized: "Suelta"), String(localized: "Ven aquí")],
             objective: String(localized: "Recoger un juguete cercano y regresar contigo."),
             materials: String(localized: "Juguete blando de tamaño adecuado y un premio para intercambiar."),
             steps: [String(localized: "Ofrece el juguete y recompensa que lo coja voluntariamente."), String(localized: "Déjalo muy cerca; al cogerlo, retrocede un paso e invítalo a volver."), String(localized: "Intercambia con «suelta» y devuelve el juguete. Añade «trae» y aumenta un poco la distancia.")],
             mistakes: [String(localized: "Lanzar lejos antes de que quiera traerlo."), String(localized: "Perseguir al perro para recuperar el juguete.")],
             progression: String(localized: "Recoge el juguete a pocos pasos y vuelve para un intercambio tranquilo."),
             precautions: String(localized: "Evita palos, pelotas pequeñas, saltos y frenadas bruscas. No todos los perros disfrutan de este juego.")),
        make("saluda", String(localized: "Saluda"), "hand.wave", .medium, .fun, prerequisites: [String(localized: "Pata")],
             objective: String(localized: "Levantar una pata brevemente como saludo, sin contacto."),
             steps: [String(localized: "Pide «pata» con la mano baja y recompensa el levantamiento inicial."), String(localized: "En otra repetición, presenta la mano algo más lejos para premiar antes del contacto."), String(localized: "Añade «saluda» y retira poco a poco la ayuda sin elevar la pata más de lo cómodo.")],
             mistakes: [String(localized: "Retirar bruscamente la mano o desequilibrarlo."), String(localized: "Buscar una postura alta o sostenida.")],
             progression: String(localized: "Levanta la pata brevemente con una pequeña señal de la mano."),
             precautions: String(localized: "Permite apoyar enseguida y usa una superficie firme. No sujetes ninguna extremidad.")),
        make("entre", String(localized: "Entre"), "arrow.down.between.lines", .medium, .coexistence, prerequisites: [String(localized: "Toca")],
             objective: String(localized: "Colocarse voluntariamente entre tus piernas abiertas."),
             steps: [String(localized: "Permanece quieto con las piernas separadas y espacio suficiente para pasar."), String(localized: "Desde detrás de ti, invita a seguir tu mano o un premio hasta el centro y recompensa."), String(localized: "Da una señal para salir. Añade «entre» antes del gesto y practica una permanencia muy breve.")],
             mistakes: [String(localized: "Cerrar las piernas sobre el cuerpo."), String(localized: "Caminar antes de que se sienta cómodo parado.")],
             progression: String(localized: "Entra con una señal y sale con libertad manteniéndose relajado."),
             precautions: String(localized: "Evítalo si el tamaño o la movilidad dificultan el paso. No lo uses para sujetarlo ni en aglomeraciones.")),
        make("sube", String(localized: "Sube"), "arrow.up.right", .medium, .coexistence,
             objective: String(localized: "Subir por iniciativa propia a una superficie baja y segura."),
             materials: String(localized: "Plataforma ancha, baja, firme y antideslizante; premios."),
             steps: [String(localized: "Permite explorar la plataforma y premia que se acerque."), String(localized: "Guía con la mano hacia ella y recompensa cada apoyo voluntario, sin tirar del cuerpo."), String(localized: "Cuando suba con comodidad, añade «sube». Enseña también una salida fácil.")],
             mistakes: [String(localized: "Elegir una altura que requiera saltar."), String(localized: "Atraerlo hacia una superficie inestable.")],
             progression: String(localized: "Sube sin impulso brusco y puede permanecer o salir con tranquilidad."),
             precautions: String(localized: "No practiques sobre muebles altos. Si necesita una rampa, introdúcela gradualmente; evita el ejercicio si hay dolor.")),
        make("baja", String(localized: "Baja"), "arrow.down.right", .easy, .coexistence,
             objective: String(localized: "Bajar con calma de una superficie baja al suelo."),
             materials: String(localized: "Superficie baja y estable, suelo antideslizante y premios."),
             steps: [String(localized: "Comprueba que puede bajar mediante un paso cómodo, sin saltar."), String(localized: "Invita a seguir tu mano hacia el suelo y recompensa cuando las cuatro patas estén apoyadas."), String(localized: "Añade «baja» antes del gesto y reduce la ayuda. Permite después descansar o explorar.")],
             mistakes: [String(localized: "Empujar, tirar del collar o levantar al perro para colocarlo."), String(localized: "Convertir la bajada en un salto alto.")],
             progression: String(localized: "Baja de una superficie conocida con la señal y sin apresurarse."),
             precautions: String(localized: "Utiliza rampa si la necesita y evita alturas. La señal no debe obligar a un movimiento doloroso."))
    ]

    private static func make(
        _ id: String, _ name: String, _ symbol: String, _ difficulty: TrickDifficulty,
        _ category: TrickCategory, prerequisites: [String] = [], objective: String,
        materials: String = String(localized: "Premios pequeños que le gusten y un entorno tranquilo."),
        steps: [String], mistakes: [String], progression: String, precautions: String
    ) -> TrickDefinition {
        TrickDefinition(
            id: id, name: name, iconIdentifier: symbol, difficulty: difficulty,
            category: category, prerequisites: prerequisites,
            guide: TrickGuide(
                objective: objective, requiredMaterials: materials, steps: steps,
                commonMistakes: mistakes,
                recommendedAttemptDuration: String(localized: "Prueba durante uno o dos minutos, o menos si pierde interés. Haz una pausa cuando lo necesite."),
                rewardGuidance: String(localized: "Marca el acierto con una palabra amable y recompensa enseguida con algo que disfrute. Cuenta los premios dentro de su alimentación."),
                progressionCriteria: progression,
                precautions: precautions + String(localized: " Detente ante señales de incomodidad y nunca fuerces la conducta.")
            )
        )
    }
}
