import Foundation

/// Original, concise guides informed by reward-based RSPCA, Dogs Trust and Blue Cross guidance.
/// No guide predicts outcomes or replaces individual professional advice.
enum BuiltInTrickLibrary {
    static let tricks: [TrickDefinition] = [
        make("sentado", "Sentado", "figure.seated.side", .easy, .basic,
             objective: "Sentarse voluntariamente al oír una señal.",
             steps: ["Acerca un premio a la nariz y muévelo despacio hacia arriba y ligeramente atrás.", "En cuanto apoye el trasero, di «bien» y entrega el premio. No empujes la cadera.", "Cuando anticipe el gesto, di «sentado» antes de hacerlo. Reduce la ayuda de la mano."],
             mistakes: ["Elevar tanto el premio que tenga que saltar.", "Pedir la postura muchas veces seguidas sin pausa."],
             progression: "Se sienta con un gesto pequeño; después prueba la señal en otra habitación.",
             precautions: "Usa suelo antideslizante. Si sentarse parece incómodo, detén el ejercicio."),
        make("quieto", "Quieto", "hand.raised", .medium, .safety, prerequisites: ["Sentado o Tumba"],
             objective: "Mantener una postura cómoda hasta la señal de terminar.",
             steps: ["Pide una postura conocida, espera un instante y recompensa sin alejarte.", "Añade «quieto» y una señal de terminar, como «ya». Libera antes de que se levante.", "Amplía primero el tiempo, luego la distancia y por último las distracciones, de una en una."],
             mistakes: ["Aumentar tiempo y distancia a la vez.", "Regañar si se mueve; vuelve a una versión más fácil."],
             progression: "Permanece relajado unos segundos mientras das un paso y regresas.",
             precautions: "Practica en un recinto seguro; esta señal nunca sustituye la correa cerca del tráfico."),
        make("ven-aqui", "Ven aquí", "arrow.down.to.line", .medium, .safety,
             objective: "Acercarse con confianza cuando lo llamas.",
             materials: "Premios valiosos; fuera de casa, arnés y correa larga en una zona segura.",
             steps: ["A poca distancia y sin distracciones, di su nombre y «ven aquí» una sola vez.", "Retrocede un par de pasos para invitarlo a acercarse. Recompensa cuando llegue.", "Permite que vuelva a explorar. Aumenta la distancia poco a poco manteniendo la seguridad."],
             mistakes: ["Llamar para regañar o terminar siempre la diversión.", "Repetir la señal si la distracción es demasiado difícil."],
             progression: "Acude desde una distancia corta en varios entornos tranquilos.",
             precautions: "No sueltes la correa para comprobar si funciona. Evita tirones y no lo persigas."),
        make("tumba", "Tumba", "arrow.down", .easy, .basic, prerequisites: ["Sentado, si resulta cómodo"],
             objective: "Tumbarse de forma relajada al recibir una señal.",
             steps: ["Desde una postura cómoda, baja un premio desde la nariz hacia el suelo.", "Deslízalo ligeramente hacia delante. Premia cualquier avance y, después, los codos apoyados.", "Añade «tumba» antes del gesto cuando lo comprenda y retira gradualmente el señuelo."],
             mistakes: ["Tirar de las patas o presionar el cuerpo.", "Mover el premio demasiado deprisa."],
             progression: "Se tumba siguiendo un gesto breve sin necesidad de comida visible.",
             precautions: "Ofrece una superficie blanda y firme. No insistas si evita apoyar el cuerpo."),
        make("dejalo", "Déjalo", "hand.raised.slash", .medium, .safety,
             objective: "Apartarse voluntariamente de un objeto antes de cogerlo.",
             steps: ["Presenta un premio dentro de una mano cerrada, sin acercarla a su cara.", "En cuanto aparte la nariz, marca y premia desde la otra mano. Si se frustra, aumenta la distancia.", "Añade «déjalo» antes de presentar la mano. Practica después con un objeto seguro a distancia."],
             mistakes: ["Usar algo peligroso para practicar.", "Dejar el objeto demasiado cerca o inaccesible durante demasiado tiempo."],
             progression: "Aparta su atención de un objeto sencillo y te mira esperando su premio.",
             precautions: "Gestiona el entorno para evitar ingestiones. Si protege objetos, pide ayuda profesional sin confrontarlo."),
        make("suelta", "Suelta", "arrow.up.forward.square", .medium, .safety,
             objective: "Soltar un juguete a cambio de algo que valore.",
             materials: "Juguete seguro y un premio o segundo juguete de valor similar o mayor.",
             steps: ["Mientras tiene un juguete sencillo, presenta un intercambio atractivo a su lado.", "Cuando abra la boca, di «bien», entrega el premio y recoge el juguete con calma.", "Devuelve el juguete cuando sea seguro. Añade «suelta» justo antes de ofrecer el intercambio."],
             mistakes: ["Perseguirlo o tirar del objeto para quitárselo.", "Quitar siempre el juguete al terminar."],
             progression: "Suelta un juguete conocido con la señal y recibe después su recompensa.",
             precautions: "No metas la mano en su boca. Si se queda rígido o protege el objeto, detente y consulta."),
        make("junto", "Junto", "figure.walk", .advanced, .coexistence,
             objective: "Caminar unos pasos a tu lado con la correa floja.",
             materials: "Arnés cómodo, correa sin tensión y premios pequeños.",
             steps: ["En un lugar tranquilo, premia cuando esté junto a tu pierna por propia iniciativa.", "Da un paso y recompensa cerca de tu lado si te acompaña con la correa floja.", "Añade «junto» y encadena pocos pasos. Alterna con ratos de olfateo libre y seguro."],
             mistakes: ["Exigir atención constante durante todo el paseo.", "Corregir con tirones al cambiar de dirección."],
             progression: "Camina varios pasos relajado junto a ti con pocas distracciones.",
             precautions: "La comodidad y el olfateo forman parte del paseo. Aumenta la distancia de lo que lo altere."),
        make("a-tu-sitio", "A tu sitio", "house", .medium, .coexistence,
             objective: "Acudir a una manta o cama y sentirse cómodo allí.",
             materials: "Manta o cama estable en una zona tranquila y premios.",
             steps: ["Coloca la manta y recompensa que se acerque o la pise voluntariamente.", "Entrega los premios sobre ella; después premia que permanezca o se tumbe.", "Di «a tu sitio» antes de que vaya. Añade una señal para salir y aumenta el tiempo con calma."],
             mistakes: ["Usar la cama como castigo.", "Esperar mucha duración cuando aún está aprendiendo."],
             progression: "Busca la manta con una señal y permanece relajado unos instantes.",
             precautions: "Debe poder alejarse. No encierres ni fuerces la permanencia."),
        make("pata", "Pata", "pawprint", .easy, .fun, prerequisites: ["Sentado cómodo"],
             objective: "Apoyar brevemente una pata en tu mano por iniciativa propia.",
             steps: ["Presenta una mano cerrada con un premio a baja altura y espera un movimiento de pata.", "Marca cualquier pequeño levantamiento y premia; después, el contacto suave con tu mano.", "Ofrece la mano vacía y premia con la otra. Añade «pata» antes del gesto."],
             mistakes: ["Agarrar o mantener levantada la pata.", "Insistir si solo olfatea o pierde interés."],
             progression: "Toca suavemente la mano abierta después de una señal.",
             precautions: "Mantén la mano baja y suelta enseguida. Detente si pierde equilibrio o muestra incomodidad."),
        make("toca", "Toca", "hand.point.up.left", .easy, .basic,
             objective: "Tocar tu mano suavemente con la nariz.",
             steps: ["Ofrece la palma abierta a pocos centímetros, a un lado de su nariz.", "Cuando se acerque y la toque, marca y recompensa desde la otra mano.", "Retira y vuelve a presentar la mano. Añade «toca» y cambia ligeramente su posición."],
             mistakes: ["Empujar la mano contra el hocico.", "Pedir que siga la mano demasiado lejos al principio."],
             progression: "Busca la palma vacía con la nariz desde pequeñas distancias.",
             precautions: "Deja espacio para retirarse y evita acercarte de frente si le incomoda."),
        make("gira", "Gira", "arrow.clockwise", .medium, .fun,
             objective: "Dar un giro amplio y suave siguiendo una señal.",
             steps: ["Con las cuatro patas en el suelo, guía la nariz con un premio en un arco amplio.", "Premia primero un cuarto de giro y después una vuelta cómoda completa.", "Añade «gira» y reduce el gesto. Haz pocas repeticiones y una pausa."],
             mistakes: ["Trazar círculos pequeños o mover el premio con rapidez.", "Encadenar giros repetidos."],
             progression: "Completa una vuelta lenta con un gesto pequeño sin perder equilibrio.",
             precautions: "Evita suelos resbaladizos. Omite este truco si hay dolor, rigidez o problemas de movilidad."),
        make("espera", "Espera", "pause", .medium, .safety,
             objective: "Hacer una pausa breve antes de avanzar con permiso.",
             steps: ["Ante una puerta interior cerrada, recompensa un instante de calma.", "Di «espera» y mueve el pomo ligeramente; premia si permanece. Reduce el movimiento si avanza.", "Abre un poco y usa «ya» para avanzar juntos. Amplía la apertura progresivamente."],
             mistakes: ["Usar una puerta a la calle como primera práctica.", "Cerrar la puerta sobre el perro para impedirle pasar."],
             progression: "Hace una pausa breve con una puerta interior abierta hasta que lo invitas a pasar.",
             precautions: "Mantén barreras físicas o correa en salidas al exterior. No confíes solo en una señal."),
        make("mirame", "Mírame", "eye", .easy, .basic,
             objective: "Orientar brevemente la atención hacia ti de manera voluntaria.",
             steps: ["En un entorno tranquilo, espera a que te mire y marca ese instante.", "Entrega un premio y deja que vuelva a mirar alrededor.", "Añade «mírame» cuando puedas anticipar la mirada. Pide solo un momento al principio."],
             mistakes: ["Mantener una mirada fija o invadir su espacio.", "Pedir atención cuando la distracción lo supera."],
             progression: "Te mira un instante al oír la señal con distracciones leves y a distancia.",
             precautions: "No exijas contacto visual prolongado. Acepta una orientación cómoda de la cabeza."),
        make("busca", "Busca", "magnifyingglass", .easy, .fun,
             objective: "Buscar pequeños premios con el olfato en una zona segura.",
             materials: "Premios apropiados y una superficie limpia sin objetos que pueda ingerir.",
             steps: ["Deja un premio a la vista en el suelo y di «busca» mientras señalas la zona.", "Permite que lo encuentre sin dirigir cada movimiento.", "Coloca después dos o tres premios fáciles de localizar y oculta alguno solo parcialmente."],
             mistakes: ["Esconder los premios en lugares demasiado difíciles.", "Ayudar constantemente o apresurar la búsqueda."],
             progression: "Explora con calma y encuentra premios parcialmente ocultos cerca.",
             precautions: "Supervisa la búsqueda, evita tóxicos y adapta los premios a su alimentación."),
        make("trae", "Trae", "arrow.uturn.backward", .advanced, .fun, prerequisites: ["Suelta", "Ven aquí"],
             objective: "Recoger un juguete cercano y regresar contigo.",
             materials: "Juguete blando de tamaño adecuado y un premio para intercambiar.",
             steps: ["Ofrece el juguete y recompensa que lo coja voluntariamente.", "Déjalo muy cerca; al cogerlo, retrocede un paso e invítalo a volver.", "Intercambia con «suelta» y devuelve el juguete. Añade «trae» y aumenta un poco la distancia."],
             mistakes: ["Lanzar lejos antes de que quiera traerlo.", "Perseguir al perro para recuperar el juguete."],
             progression: "Recoge el juguete a pocos pasos y vuelve para un intercambio tranquilo.",
             precautions: "Evita palos, pelotas pequeñas, saltos y frenadas bruscas. No todos los perros disfrutan de este juego."),
        make("saluda", "Saluda", "hand.wave", .medium, .fun, prerequisites: ["Pata"],
             objective: "Levantar una pata brevemente como saludo, sin contacto.",
             steps: ["Pide «pata» con la mano baja y recompensa el levantamiento inicial.", "En otra repetición, presenta la mano algo más lejos para premiar antes del contacto.", "Añade «saluda» y retira poco a poco la ayuda sin elevar la pata más de lo cómodo."],
             mistakes: ["Retirar bruscamente la mano o desequilibrarlo.", "Buscar una postura alta o sostenida."],
             progression: "Levanta la pata brevemente con una pequeña señal de la mano.",
             precautions: "Permite apoyar enseguida y usa una superficie firme. No sujetes ninguna extremidad."),
        make("entre", "Entre", "arrow.down.between.lines", .medium, .coexistence, prerequisites: ["Toca"],
             objective: "Colocarse voluntariamente entre tus piernas abiertas.",
             steps: ["Permanece quieto con las piernas separadas y espacio suficiente para pasar.", "Desde detrás de ti, invita a seguir tu mano o un premio hasta el centro y recompensa.", "Da una señal para salir. Añade «entre» antes del gesto y practica una permanencia muy breve."],
             mistakes: ["Cerrar las piernas sobre el cuerpo.", "Caminar antes de que se sienta cómodo parado."],
             progression: "Entra con una señal y sale con libertad manteniéndose relajado.",
             precautions: "Evítalo si el tamaño o la movilidad dificultan el paso. No lo uses para sujetarlo ni en aglomeraciones."),
        make("sube", "Sube", "arrow.up.right", .medium, .coexistence,
             objective: "Subir por iniciativa propia a una superficie baja y segura.",
             materials: "Plataforma ancha, baja, firme y antideslizante; premios.",
             steps: ["Permite explorar la plataforma y premia que se acerque.", "Guía con la mano hacia ella y recompensa cada apoyo voluntario, sin tirar del cuerpo.", "Cuando suba con comodidad, añade «sube». Enseña también una salida fácil."],
             mistakes: ["Elegir una altura que requiera saltar.", "Atraerlo hacia una superficie inestable."],
             progression: "Sube sin impulso brusco y puede permanecer o salir con tranquilidad.",
             precautions: "No practiques sobre muebles altos. Si necesita una rampa, introdúcela gradualmente; evita el ejercicio si hay dolor."),
        make("baja", "Baja", "arrow.down.right", .easy, .coexistence,
             objective: "Bajar con calma de una superficie baja al suelo.",
             materials: "Superficie baja y estable, suelo antideslizante y premios.",
             steps: ["Comprueba que puede bajar mediante un paso cómodo, sin saltar.", "Invita a seguir tu mano hacia el suelo y recompensa cuando las cuatro patas estén apoyadas.", "Añade «baja» antes del gesto y reduce la ayuda. Permite después descansar o explorar."],
             mistakes: ["Empujar, tirar del collar o levantar al perro para colocarlo.", "Convertir la bajada en un salto alto."],
             progression: "Baja de una superficie conocida con la señal y sin apresurarse.",
             precautions: "Utiliza rampa si la necesita y evita alturas. La señal no debe obligar a un movimiento doloroso.")
    ]

    private static func make(
        _ id: String, _ name: String, _ symbol: String, _ difficulty: TrickDifficulty,
        _ category: TrickCategory, prerequisites: [String] = [], objective: String,
        materials: String = "Premios pequeños que le gusten y un entorno tranquilo.",
        steps: [String], mistakes: [String], progression: String, precautions: String
    ) -> TrickDefinition {
        TrickDefinition(
            id: id, name: name, iconIdentifier: symbol, difficulty: difficulty,
            category: category, prerequisites: prerequisites,
            guide: TrickGuide(
                objective: objective, requiredMaterials: materials, steps: steps,
                commonMistakes: mistakes,
                recommendedAttemptDuration: "Prueba durante uno o dos minutos, o menos si pierde interés. Haz una pausa cuando lo necesite.",
                rewardGuidance: "Marca el acierto con una palabra amable y recompensa enseguida con algo que disfrute. Cuenta los premios dentro de su alimentación.",
                progressionCriteria: progression,
                precautions: precautions + " Detente ante señales de incomodidad y nunca fuerces la conducta."
            )
        )
    }
}
